# PATH to this config
$path = /home/alex/.config/hypr

# Theme
source=~/.config/hypr/themes/mocha.conf

# This config is splitted into multiple files, import then
source = ./config/monitors.conf
source = ./config/autostart.conf
source = ./config/env_var.conf
source = ./config/inputs.conf
source = ./config/keybindings.conf
source = ./config/rules.conf
