################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/

# Laptop
monitor=eDP-2,2560x1600@120,auto,1.6
# Other
monitor=,preferred,auto,1

exec = $path/scripts/set_monitors.sh
